# Generated by Django 5.1.6 on 2025-03-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockalert_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_charge_percent',
            field=models.FloatField(default=5),
        ),
    ]
