# Generated by Django 5.1.6 on 2025-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_extra_charge_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='transaction_amount',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='extra_charge_percent',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale')], max_length=10),
        ),
    ]
