# Generated by Django 5.1.6 on 2025-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorytransaction_transaction_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='extra_charge_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_charge_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
