# Generated by Django 5.1.6 on 2025-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='excel_data',
            field=models.JSONField(blank=True, help_text='Stores the latest uploaded Excel data', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_using_excel',
            field=models.BooleanField(default=False, help_text='Whether to use Excel data for responses'),
        ),
    ]
